export enum HttpResponse {
    SERVER_ERROR = "Internal server error",
    USER_EXIST = "User already exist",
    PAGE_NOT_FOUND = "Route not found",
    USER_NOT_FOUND = "User not found",
    PASSWORD_INCORRECT = "Incorrect password, try again",
    NO_TOKEN = "Token not provided",
    INVALID_CREDENTIALS = "Invalid credentials",
    USER_CREATION_FAILED = "User creation failed",
    USER_CREATION_SUCCESS = "User created successfully",
    EMAIL_EXIST = "Email already exist",
    INVALID_EMAIL = "Invalid email address",
    UNEXPECTED_KEY_FOUND = "Unexpected key found",
    TOKEN_EXPIRED = "Token not valid or expired!",
    UNAUTHORIZED = "Unauthorized access!",
    USERNAME_EXIST = "Username Already Exist",
    USERNAME_CHANGED = "Username has been changed successfully",
    SAME_USERNAME = "Cannot change to old username",
    RESOURCE_FOUND = "Resource found.",
    RESOURCE_UPDATED = "Resource updated.",
    PROFILE_PICTURE_CHANGED = "Profile picture changed successfully",
    LOGOUT_SUCCESS = "User Logout successfully",
    INVALID_ID = "Invalid ID format",
    REQUIRED_AUTHOR_ID = "Author ID is required",
    REQUIRED_AUTHOR_NAME = "Author name is required",
    TOO_MANY_REQUESTS = "Too many requests, please try again later.",
    INVALID_USERNAME = "Invalid username",
}; 
